import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <nav style={{ padding: "16px", borderBottom: "1px solid white" }}>
        <strong>Wall Crawl Nation</strong>
        <Link href="/" style={{ marginLeft: "20px" }}>
          Home
        </Link>
        <Link href="/shop" style={{ marginLeft: "12px" }}>
          Shop
        </Link>          
        <Link href="/cart" style={{ marginLeft: "12px" }}>
          Cart
        </Link>
      </nav>

      <main style={{ padding: "24px" }}>
        {children}
      </main>
    </body>

    </html>
  );
}
